### ISSUE TITLE
Still relevant in 2016?

### ISSUE THREAD

**Issue by daxfohl** [typesafehub/webwords#8]
This project *seems like* the basis of the sort of thing I'm needing to do now (website with messages sent to background workers).  Is this still the way you'd recommend going about it?  In particular would finagle perhaps be a better front end?  Is RabbitMQ (or message queues in general) still the best way to communicate with background workers?

**Comment by wsargent** [comment]
@daxfohl this is very old.  

I would look at Play 2.5.0 and use the Akka integration there.  Heroku works with SBT out of the box: https://devcenter.heroku.com/articles/getting-started-with-scala#introduction so there's not the motivation for this that there once was.

You can post on https://groups.google.com/forum/#!forum/play-framework with more details about your requirements, but there are many, many Activator templates out there that are better examples these days, such as Reactive Maps: https://www.playframework.com/documentation/2.5.x/Tutorials#Reactive-Maps
